# Generated by Django 2.2.1 on 2019-05-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('ISBN', models.CharField(default='', max_length=255)),
                ('author', models.CharField(default='', max_length=255)),
                ('class_id', models.IntegerField(default=0)),
                ('publish_date', models.DateField()),
                ('is_order', models.BooleanField(default=False)),
                ('location', models.CharField(default='', max_length=255, null=True)),
                ('UUID', models.CharField(default='', max_length=255, null=True)),
                ('e_book_id', models.IntegerField(null=True)),
                ('is_reservation', models.BooleanField(default=False)),
            ],
        ),
    ]
