# Generated by Django 2.2.1 on 2019-05-24 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libsys', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField(default=0, max_length=255)),
                ('reader_id', models.IntegerField(default=0, max_length=255)),
                ('num', models.IntegerField(default='', max_length=255)),
                ('book_name', models.CharField(default='', max_length=255)),
                ('date', models.DateField()),
                ('is_overdue', models.BooleanField(default=False)),
                ('retuen_date', models.DateField()),
            ],
        ),
    ]
