# Generated by Django 2.2.1 on 2019-05-24 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libsys', '0002_borrow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='book_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='num',
            field=models.IntegerField(default=''),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='reader_id',
            field=models.IntegerField(default=0),
        ),
    ]
