# Generated by Django 2.2.1 on 2019-05-24 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libsys', '0003_auto_20190525_0214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='publish_date',
        ),
    ]
