# Generated by Django 2.2.1 on 2019-05-25 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libsys', '0004_remove_book_publish_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(default='', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='E_book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('auther', models.CharField(default='', max_length=255)),
                ('ISBN', models.CharField(default='', max_length=255)),
                ('class_id', models.IntegerField(default=0)),
                ('publish_data', models.DateField()),
                ('is_order', models.BooleanField(default=False)),
                ('location', models.CharField(default='', max_length=255)),
                ('UUID', models.CharField(default='', max_length=255)),
                ('lib_name', models.CharField(default='', max_length=255)),
                ('is_open', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('date', models.DateField()),
                ('user_id', models.IntegerField(default=0)),
                ('content', models.CharField(default='', max_length=255)),
                ('parent_menu', models.CharField(default='', max_length=255)),
                ('is_reading', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('book_num', models.IntegerField(default=0)),
                ('max_num', models.IntegerField(default=0)),
                ('account', models.CharField(default='', max_length=255)),
                ('password', models.CharField(default='', max_length=255)),
                ('level', models.IntegerField(default=0)),
                ('overdue_time', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Reader_level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0)),
                ('name', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Reserve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.IntegerField(default=0)),
                ('reader_id', models.IntegerField(default=0)),
                ('num', models.IntegerField(default=0)),
                ('book_name', models.CharField(default='', max_length=255)),
                ('data', models.DateField()),
                ('is_overdue', models.BooleanField(default=False)),
            ],
        ),
    ]
