# Generated by Django 2.2.1 on 2019-05-25 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libsys', '0005_book_class_e_book_message_reader_reader_level_reserve'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book_class',
            new_name='BookClass',
        ),
        migrations.RenameModel(
            old_name='E_book',
            new_name='EBook',
        ),
        migrations.RenameModel(
            old_name='Reader_level',
            new_name='ReaderLevel',
        ),
    ]
