# Generated by Django 2.2.2 on 2019-06-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libsys', '0007_book_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publish_name',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
