# Generated by Django 2.2.2 on 2019-06-18 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libsys', '0009_book_publish_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrow',
            old_name='retuen_date',
            new_name='return_date',
        ),
    ]
